"""
make_openai_vlm_batch_gpt55_xhigh.py
====================================
Create an OpenAI Batch API JSONL file for the blinded VLM realism audit.

The generated batch targets the Responses API with gpt-5.5 and xhigh
reasoning. It uses the existing blinded image_index.csv as the source of truth,
not every loose PNG in the audit image folder.
"""

from __future__ import annotations

import argparse
import base64
import csv
import json
from pathlib import Path


DEFAULT_AUDIT_ROOT = Path(
    "outputs_v2/vlm_realism_audits/vlm_realism_train_augmented_r2_all"
)
DEFAULT_OUT_DIR = Path(
    "outputs_v2/openai_batch/vlm_realism_train_augmented_r2_gpt55_xhigh"
)

SYSTEM_PROMPT = """\
You are an automated visual-realism judge for a blinded research audit of
preprocessed brain MRI images. This is not a clinical diagnostic task, and your
answers must not be interpreted as medical advice. Your role is to judge visual
plausibility and forced-choice labels for research scoring only.

All images are anonymized, preprocessed, normalized 128 x 128 MRI-like images.
Some are real BRISC images and some are synthetic images generated by a
StyleGAN2-ADA model. File names and image IDs are random blinded identifiers;
do not infer anything from them. Use image content only.

Think carefully before answering, but output only the requested JSON object.
Do not reveal chain-of-thought. If uncertain, still provide the best
forced-choice answer and lower the corresponding confidence.
"""

USER_PROMPT_TEMPLATE = """\
Evaluate this blinded image for a research-only real-vs-synthetic realism
audit.

Image ID: {image_id}
Filename: {filename}

Return:
1. Whether the image is a usable brain-MRI-like image for this audit.
2. The apparent tumour class, forced choice: glioma, meningioma, no_tumor, or
   pituitary.
3. The apparent plane, forced choice: ax, co, or sa.
4. The apparent source, forced choice: real or synthetic.
5. A realism score from 1 to 5, where 1 means clearly synthetic or implausible
   and 5 means indistinguishable from a real preprocessed MRI.
6. Any visible artifact categories.

Do not call the image synthetic merely because it is small, cropped,
preprocessed, grayscale/RGB encoded, or normalized. Those properties apply to
both real and synthetic images in this audit.
"""


def response_schema() -> dict:
    artifact_enum = [
        "none_obvious",
        "texture_artifact",
        "anatomy_implausible",
        "edge_or_crop_artifact",
        "contrast_or_intensity_artifact",
        "noise_pattern_artifact",
        "repetition_or_symmetry_artifact",
        "other",
    ]
    return {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "image_id": {"type": "string"},
            "filename": {"type": "string"},
            "usable_brain_mri_like_image": {"type": "boolean"},
            "tumour_class": {
                "type": "string",
                "enum": ["glioma", "meningioma", "no_tumor", "pituitary"],
            },
            "tumour_confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
            },
            "plane": {
                "type": "string",
                "enum": ["ax", "co", "sa"],
            },
            "plane_confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
            },
            "source_prediction": {
                "type": "string",
                "enum": ["real", "synthetic"],
            },
            "source_confidence": {
                "type": "number",
                "minimum": 0,
                "maximum": 1,
            },
            "realism_score": {
                "type": "integer",
                "minimum": 1,
                "maximum": 5,
            },
            "artifact_categories": {
                "type": "array",
                "items": {"type": "string", "enum": artifact_enum},
            },
            "rationale": {
                "type": "string",
                "description": "Concise visible-evidence rationale, maximum 40 words.",
            },
        },
        "required": [
            "image_id",
            "filename",
            "usable_brain_mri_like_image",
            "tumour_class",
            "tumour_confidence",
            "plane",
            "plane_confidence",
            "source_prediction",
            "source_confidence",
            "realism_score",
            "artifact_categories",
            "rationale",
        ],
    }


def read_image_index(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"Image index is empty: {path}")
    seen = set()
    for row in rows:
        image_id = row.get("image_id", "")
        filename = row.get("filename", "")
        if not image_id or not filename:
            raise ValueError(f"Malformed image_index row: {row}")
        if image_id in seen:
            raise ValueError(f"Duplicate image_id in image index: {image_id}")
        seen.add(image_id)
    return rows


def image_data_url(path: Path) -> str:
    data = path.read_bytes()
    return "data:image/png;base64," + base64.b64encode(data).decode("ascii")


def make_request(row: dict[str, str], image_path: Path, model: str,
                 reasoning_effort: str, max_output_tokens: int) -> dict:
    image_id = row["image_id"]
    filename = row["filename"]
    return {
        "custom_id": f"vlm-realism-{image_id}",
        "method": "POST",
        "url": "/v1/responses",
        "body": {
            "model": model,
            "reasoning": {"effort": reasoning_effort},
            "max_output_tokens": max_output_tokens,
            "store": False,
            "input": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_text",
                            "text": USER_PROMPT_TEMPLATE.format(
                                image_id=image_id,
                                filename=filename,
                            ),
                        },
                        {
                            "type": "input_image",
                            "image_url": image_data_url(image_path),
                            "detail": "original",
                        },
                    ],
                },
            ],
            "text": {
                "format": {
                    "type": "json_schema",
                    "name": "vlm_realism_audit_response",
                    "strict": True,
                    "schema": response_schema(),
                }
            },
        },
    }


def write_submit_helper(path: Path, shard_names: list[str]) -> None:
    shard_list = ",\n    ".join(repr(name) for name in shard_names)
    text = f"""\
from pathlib import Path

from openai import OpenAI

HERE = Path(__file__).resolve().parent
SHARDS = [
    {shard_list}
]
client = OpenAI()

for shard_name in SHARDS:
    shard_path = HERE / "jsonl_shards" / shard_name
    batch_input_file = client.files.create(
        file=open(shard_path, "rb"),
        purpose="batch",
    )

    batch = client.batches.create(
        input_file_id=batch_input_file.id,
        endpoint="/v1/responses",
        completion_window="24h",
        metadata={{
            "description": f"BRISC blinded VLM audit, gpt-5.5 xhigh, {{shard_name}}",
            "project": "RA1",
            "shard": shard_name,
        }},
    )

    print(shard_name)
    print("  input_file_id:", batch_input_file.id)
    print("  batch_id:", batch.id)
    print("  status:", batch.status)
"""
    path.write_text(text, encoding="utf-8")


def write_readme(path: Path, shard_names: list[str]) -> None:
    shard_lines = "\n".join(f"- `jsonl_shards/{name}`" for name in shard_names)
    text = f"""\
# GPT-5.5 xhigh blinded VLM realism audit batch

This folder contains the OpenAI Batch API input for the blinded BRISC
real-vs-synthetic realism audit.

Files:

- JSONL shards, max 400 requests each:
{shard_lines}
- `batch_index.csv`: blinded request map, no true labels.
- `batch_summary.json`: creation metadata and validation summary.
- `submit_wave1_gpt55_xhigh.py`: uploads/creates the first five batch jobs.
- `submit_wave2_gpt55_xhigh.py`: uploads/creates the remaining final batch job.

The private answer key remains in the original audit package and is not embedded
in the batch input. Results must be scored only after the batch output is
downloaded.

Submission, wave 1:

```powershell
cd C:\\Users\\norie\\OneDrive\\RA1\\outputs_v2\\openai_batch\\vlm_realism_train_augmented_r2_gpt55_xhigh
python submit_wave1_gpt55_xhigh.py
```

After those five finish, submit wave 2:

```powershell
python submit_wave2_gpt55_xhigh.py
```
"""
    path.write_text(text, encoding="utf-8")


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Build gpt-5.5 xhigh OpenAI Batch JSONL for VLM audit."
    )
    parser.add_argument("--project-root", type=Path, default=Path(__file__).parent)
    parser.add_argument("--audit-root", type=Path, default=DEFAULT_AUDIT_ROOT)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--model", default="gpt-5.5")
    parser.add_argument("--reasoning-effort", default="xhigh")
    parser.add_argument("--max-output-tokens", type=int, default=700)
    parser.add_argument("--requests-per-file", type=int, default=400)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--force", action="store_true")
    return parser.parse_args(argv)


def main(argv=None) -> None:
    args = parse_args(argv)
    project_root = args.project_root.resolve()
    audit_root = args.audit_root
    if not audit_root.is_absolute():
        audit_root = project_root / audit_root
    audit_root = audit_root.resolve()
    out_dir = args.out_dir
    if not out_dir.is_absolute():
        out_dir = project_root / out_dir
    out_dir = out_dir.resolve()

    image_index_path = audit_root / "public" / "image_index.csv"
    images_dir = audit_root / "public" / "images"
    private_key_path = audit_root / "private" / "answer_key.csv"
    if not image_index_path.is_file():
        raise SystemExit(f"Missing image index: {image_index_path}")
    if not images_dir.is_dir():
        raise SystemExit(f"Missing image directory: {images_dir}")
    if not private_key_path.is_file():
        raise SystemExit(f"Missing private answer key: {private_key_path}")

    if args.requests_per_file <= 0:
        raise SystemExit("--requests-per-file must be positive.")
    if out_dir.exists() and any(out_dir.iterdir()):
        if not args.force:
            raise SystemExit(f"Output directory is not empty: {out_dir}. Use --force.")
    out_dir.mkdir(parents=True, exist_ok=True)
    shard_dir = out_dir / "jsonl_shards"
    shard_dir.mkdir(parents=True, exist_ok=True)
    if args.force:
        for stale_file in [
            out_dir / "vlm_realism_gpt55_xhigh_batch.jsonl",
            out_dir / "submit_batch_gpt55_xhigh.py",
            out_dir / "submit_wave1_gpt55_xhigh.py",
            out_dir / "submit_wave2_gpt55_xhigh.py",
            out_dir / "batch_index.csv",
            out_dir / "batch_summary.json",
            out_dir / "README.md",
        ]:
            if stale_file.exists():
                stale_file.unlink()
        for stale_shard in shard_dir.glob("*.jsonl"):
            stale_shard.unlink()

    rows = read_image_index(image_index_path)
    if args.limit is not None:
        if args.limit <= 0:
            raise SystemExit("--limit must be positive.")
        rows = rows[:args.limit]

    batch_index_path = out_dir / "batch_index.csv"

    total_png_bytes = 0
    shard_paths = []
    shard_request_counts = []
    current_shard = None
    current_count = 0
    shard_no = 0

    with batch_index_path.open("w", encoding="utf-8", newline="") as f_csv:
        writer = csv.DictWriter(
            f_csv,
            fieldnames=["custom_id", "image_id", "filename", "image_path", "shard"],
        )
        writer.writeheader()
        try:
            for row in rows:
                if current_shard is None or current_count >= args.requests_per_file:
                    if current_shard is not None:
                        current_shard.close()
                        shard_request_counts.append(current_count)
                    shard_no += 1
                    shard_path = shard_dir / (
                        f"vlm_realism_gpt55_xhigh_batch_{shard_no:03d}.jsonl"
                    )
                    shard_paths.append(shard_path)
                    current_shard = shard_path.open(
                        "w", encoding="utf-8", newline="\n"
                    )
                    current_count = 0

                image_path = images_dir / row["filename"]
                if not image_path.is_file():
                    raise FileNotFoundError(f"Missing indexed image: {image_path}")
                total_png_bytes += image_path.stat().st_size
                request = make_request(
                    row=row,
                    image_path=image_path,
                    model=args.model,
                    reasoning_effort=args.reasoning_effort,
                    max_output_tokens=args.max_output_tokens,
                )
                current_shard.write(json.dumps(request, separators=(",", ":")) + "\n")
                current_count += 1
                writer.writerow({
                    "custom_id": request["custom_id"],
                    "image_id": row["image_id"],
                    "filename": row["filename"],
                    "image_path": str(image_path),
                    "shard": shard_paths[-1].name,
                })
        finally:
            if current_shard is not None:
                current_shard.close()
                shard_request_counts.append(current_count)

    # Validate JSONL and single endpoint/model invariants required by Batch.
    custom_ids = set()
    for shard_path, shard_count in zip(shard_paths, shard_request_counts):
        if shard_count > args.requests_per_file:
            raise ValueError(f"Shard exceeds request cap: {shard_path}")
        with shard_path.open(encoding="utf-8") as f:
            for line_no, line in enumerate(f, start=1):
                obj = json.loads(line)
                custom_id = obj["custom_id"]
                if custom_id in custom_ids:
                    raise ValueError(
                        f"Duplicate custom_id at {shard_path}:{line_no}: {custom_id}"
                    )
                custom_ids.add(custom_id)
                if obj["method"] != "POST":
                    raise ValueError(f"Non-POST method at {shard_path}:{line_no}")
                if obj["url"] != "/v1/responses":
                    raise ValueError(
                        f"Wrong endpoint at {shard_path}:{line_no}: {obj['url']}"
                    )
                body = obj["body"]
                if body["model"] != args.model:
                    raise ValueError(
                        f"Wrong model at {shard_path}:{line_no}: {body['model']}"
                    )
                if body["reasoning"]["effort"] != args.reasoning_effort:
                    raise ValueError(f"Wrong effort at {shard_path}:{line_no}")

    shard_sizes = [path.stat().st_size for path in shard_paths]
    summary = {
        "jsonl_shards": [str(path) for path in shard_paths],
        "batch_index": str(batch_index_path),
        "audit_root": str(audit_root),
        "image_index": str(image_index_path),
        "private_answer_key_not_embedded": str(private_key_path),
        "endpoint": "/v1/responses",
        "model": args.model,
        "reasoning_effort": args.reasoning_effort,
        "image_detail": "original",
        "n_requests": len(rows),
        "requests_per_file_cap": args.requests_per_file,
        "n_jsonl_shards": len(shard_paths),
        "shard_request_counts": shard_request_counts,
        "shard_bytes": shard_sizes,
        "total_indexed_png_bytes": total_png_bytes,
        "total_jsonl_bytes": sum(shard_sizes),
        "total_jsonl_mb": round(sum(shard_sizes) / 1024 / 1024, 3),
        "all_shards_under_200mb_batch_upload_limit": all(
            size < 200 * 1024 * 1024 for size in shard_sizes
        ),
        "max_output_tokens": args.max_output_tokens,
        "structured_output": "strict json_schema",
    }
    (out_dir / "batch_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )
    shard_names = [path.name for path in shard_paths]
    write_submit_helper(out_dir / "submit_wave1_gpt55_xhigh.py", shard_names[:5])
    write_submit_helper(out_dir / "submit_wave2_gpt55_xhigh.py", shard_names[5:])
    write_readme(out_dir / "README.md", shard_names)

    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
